In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import re
import math

In [2]:
import warnings
warnings.filterwarnings("ignore")

# Creating series

In [3]:
v=np.array([1,2,3,4,5,6])
s1=pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [4]:
s1.dtype

dtype('int64')

In [5]:
s1.itemsize

AttributeError: 'Series' object has no attribute 'itemsize'

In [ ]:
s1.nbytes

In [6]:
s1.shape

(6,)

In [7]:
s1.ndim

1

In [8]:
len(s1)

6

In [9]:
s1.count()

np.int64(6)

In [10]:
s1.size

6

In [11]:
s0=pd.Series([1,2,3],index=[ 'a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [12]:
s1.index=['a' , 'b' , 'c' , 'd' , 'e' , 'f' ]
s1

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [13]:
v2=np.random.random(10)
ind2=np.arange(0,10)
s=pd.Series(v2,ind2)
v2,ind2,s

(array([0.87843811, 0.99520983, 0.24746051, 0.61583208, 0.77101278,
        0.79402851, 0.48789372, 0.86883798, 0.65520575, 0.21278012]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.878438
 1    0.995210
 2    0.247461
 3    0.615832
 4    0.771013
 5    0.794029
 6    0.487894
 7    0.868838
 8    0.655206
 9    0.212780
 dtype: float64)

In [14]:
dict1={'a1' :10, 'a2' :20, 'a3':30, 'a4':40}
s3=pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [15]:
pd.Series(99, index=[0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

# Slicing Series

In [16]:
s

0    0.878438
1    0.995210
2    0.247461
3    0.615832
4    0.771013
5    0.794029
6    0.487894
7    0.868838
8    0.655206
9    0.212780
dtype: float64

In [17]:
s[:]

0    0.878438
1    0.995210
2    0.247461
3    0.615832
4    0.771013
5    0.794029
6    0.487894
7    0.868838
8    0.655206
9    0.212780
dtype: float64

In [18]:
s[0:3]

0    0.878438
1    0.995210
2    0.247461
dtype: float64

In [19]:
s[-1:]

9    0.21278
dtype: float64

In [20]:
s[:4]

0    0.878438
1    0.995210
2    0.247461
3    0.615832
dtype: float64

In [21]:
s[:-2]

0    0.878438
1    0.995210
2    0.247461
3    0.615832
4    0.771013
5    0.794029
6    0.487894
7    0.868838
dtype: float64

In [22]:
s[:-1]

0    0.878438
1    0.995210
2    0.247461
3    0.615832
4    0.771013
5    0.794029
6    0.487894
7    0.868838
8    0.655206
dtype: float64

In [23]:
s[-2:]

8    0.655206
9    0.212780
dtype: float64

In [24]:
s[-1:]

9    0.21278
dtype: float64

In [25]:
s[-3:-1]

7    0.868838
8    0.655206
dtype: float64

# Append Series

In [26]:
s2=s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [27]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [28]:
import pandas as pd

s4 = pd.concat([s2, s3])
print(s4)

a      1
b      2
c      3
d      4
e      5
f      6
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [29]:
s4.drop('a4', inplace=False)

a      1
b      2
c      3
d      4
e      5
f      6
a1    10
a2    20
a3    30
dtype: int64

In [30]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [31]:
s4.drop('a4', inplace=True)
s4

a      1
b      2
c      3
d      4
e      5
f      6
a1    10
a2    20
a3    30
dtype: int64

In [32]:
s4 = pd.concat([s4, pd.Series({'a4': 7})])
print(s4)

a      1
b      2
c      3
d      4
e      5
f      6
a1    10
a2    20
a3    30
a4     7
dtype: int64

# Operastion in Series

In [33]:
v1=np.array([10,20,30])
v2=np.array([1,2,3])
s1=pd.Series(v1)
s2=pd.Series(v2)
s1 , s2

(0    10
 1    20
 2    30
 dtype: int64,
 0    1
 1    2
 2    3
 dtype: int64)

In [34]:
s1.add(s2)

0    11
1    22
2    33
dtype: int64

In [35]:
s1.sub(s2)

0     9
1    18
2    27
dtype: int64

In [36]:
s1.subtract(s2)

0     9
1    18
2    27
dtype: int64

In [37]:
s1.add(9)

0    19
1    29
2    39
dtype: int64

In [38]:
s1.mul(s2)

0    10
1    40
2    90
dtype: int64

In [39]:
s1.multiply(s2)

0    10
1    40
2    90
dtype: int64

In [40]:
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int64

In [41]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [42]:
s1.div(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [43]:
s1.max()

30

In [44]:
s1.min()

10

In [45]:
s1.median()

20.0

In [46]:
s1.std()

10.0

In [47]:
s1.equals(s2)

False

In [48]:
s4=s1

In [49]:
s1.equals(s4)

True

In [50]:
s5=pd.Series([1,1,2,2,3,3], index=[0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [51]:
s5.value_counts()

1    2
2    2
3    2
Name: count, dtype: int64

# DataFrame

# create data frame

In [52]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [53]:
lang=['Java', 'Python', 'C', 'C++']
df=pd.DataFrame(lang)
df

        0
0    Java
1  Python
2       C
3     C++

In [54]:
rating=[1,2,3,4]
df[1]=rating
df

        0  1
0    Java  1
1  Python  2
2       C  3
3     C++  4

In [55]:
df.columns=['Language','Rating']
df

  Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [56]:
data=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]

df2=pd.DataFrame(data)
df3=pd.DataFrame(data, index=['row1', 'row2'], columns=['a', 'b'])
df4 = pd.DataFrame(data, index=['row1', 'row2'], columns=['a', 'b' ,'c'])
df5 = pd.DataFrame(data, index=['row1', 'row2'], columns=['a', 'b' ,'c' , 'd'])
df2

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [57]:
df3

      a   b
row1  1   2
row2  5  10

In [58]:
df4

      a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [59]:
df5

      a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [60]:
df0=pd.DataFrame({'ID' :[1,2,3,4], 'Name' :['Asif', 'Basit', 'Ross', 'John']})
df0

   ID   Name
0   1   Asif
1   2  Basit
2   3   Ross
3   4   John

In [61]:
dict ={'A' : pd.Series([1,2,3], index=['a', 'b', 'c']),
      'B' : pd.Series([1,2,3,4], index=['a','b','c','d'])}

df1=pd.DataFrame(dict)
df1

     A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

# DataFrame of Random Numbers with Date Indices

In [62]:
dates=pd.date_range(start='2020-01-20' , end='2020-01-26')
dates

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26'],
              dtype='datetime64[ns]', freq='D')

In [63]:
dates=pd.date_range('today',periods=7)
dates

DatetimeIndex(['2026-05-27 12:03:25.083360', '2026-05-28 12:03:25.083360',
               '2026-05-29 12:03:25.083360', '2026-05-30 12:03:25.083360',
               '2026-05-31 12:03:25.083360', '2026-06-01 12:03:25.083360',
               '2026-06-02 12:03:25.083360'],
              dtype='datetime64[ns]', freq='D')

In [64]:
dates=pd.date_range(start='2020-01-20',periods=7)
dates

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26'],
              dtype='datetime64[ns]', freq='D')

In [65]:
M=np.random.random((7,7))
M

array([[0.57377997, 0.21066467, 0.65283067, 0.50551964, 0.44294656,
        0.71782032, 0.03113381],
       [0.22698774, 0.15525614, 0.74455117, 0.460331  , 0.51380697,
        0.71423186, 0.37018151],
       [0.70713418, 0.45271288, 0.53865449, 0.79557731, 0.00592723,
        0.16298831, 0.17469417],
       [0.84358591, 0.55524273, 0.39927582, 0.02014486, 0.93751366,
        0.45727931, 0.81053642],
       [0.98060107, 0.43274681, 0.2296712 , 0.28893072, 0.24382753,
        0.47972603, 0.70906011],
       [0.12686767, 0.48112893, 0.140612  , 0.28184022, 0.48874475,
        0.28529592, 0.82467151],
       [0.18570889, 0.75184843, 0.09268111, 0.19476232, 0.28839299,
        0.07306302, 0.07368167]])

In [66]:
dframe=pd.DataFrame(M, index=dates)
dframe

,0,1,2,3,4,5,6
2020-01-20,0.573780,0.210665,0.652831,0.505520,0.442947,0.717820,0.031134
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682

In [67]:
dframe.columns=['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,0.573780,0.210665,0.652831,0.505520,0.442947,0.717820,0.031134
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682

In [68]:
dframe.index

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26'],
              dtype='datetime64[ns]', freq='D')

In [69]:
dframe.columns

Index(['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7'], dtype='object')

In [70]:
dframe.dtypes

C1    float64
C2    float64
C3    float64
C4    float64
C5    float64
C6    float64
C7    float64
dtype: object

In [71]:
dframe.sort_values(by='C1')

,C1,C2,C3,C4,C5,C6,C7
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182
2020-01-20,0.573780,0.210665,0.652831,0.505520,0.442947,0.717820,0.031134
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060

# Delete Columns in DataFrame

In [72]:
df1

     A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

In [73]:
del df1['B']

In [74]:
df1

     A
a  1.0
b  2.0
c  3.0
d  NaN

In [75]:
df5

      a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [76]:
df5.pop('c')

row1     NaN
row2    20.0
Name: c, dtype: float64

In [77]:
df5

      a   b   d
row1  1   2 NaN
row2  5  10 NaN

In [78]:
dict = {'A' : pd.Series([1, 2, 3,11],    index=['a', 'b', 'c','d']),
        'B' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df12 = pd.DataFrame(dict)
df12

    A  B
a   1  1
b   2  2
c   3  3
d  11  4

# Delete Rows in DataFrame

In [79]:
col1=np.linspace(10,100,30)
col2=np.random.randint(10,100,30)
df10=pd.DataFrame({"C1": col1,"C2": col2})
df10

            C1  C2
0    10.000000  32
1    13.103448  47
2    16.206897  84
3    19.310345  96
4    22.413793  76
5    25.517241  93
6    28.620690  58
7    31.724138  14
8    34.827586  36
9    37.931034  96
10   41.034483  75
11   44.137931  12
12   47.241379  63
13   50.344828  65
14   53.448276  61
15   56.551724  79
16   59.655172  54
17   62.758621  21
18   65.862069  19
19   68.965517  77
20   72.068966  47
21   75.172414  63
22   78.275862  46
23   81.379310  90
24   84.482759  68
25   87.586207  49
26   90.689655  23
27   93.793103  55
28   96.896552  24
29  100.000000  82

In [80]:
df10=df10.drop([17,18,19],axis=0)
df10

            C1  C2
0    10.000000  32
1    13.103448  47
2    16.206897  84
3    19.310345  96
4    22.413793  76
5    25.517241  93
6    28.620690  58
7    31.724138  14
8    34.827586  36
9    37.931034  96
10   41.034483  75
11   44.137931  12
12   47.241379  63
13   50.344828  65
14   53.448276  61
15   56.551724  79
16   59.655172  54
20   72.068966  47
21   75.172414  63
22   78.275862  46
23   81.379310  90
24   84.482759  68
25   87.586207  49
26   90.689655  23
27   93.793103  55
28   96.896552  24
29  100.000000  82

In [81]:
df10.drop([16],axis=0,inplace=True)
df10

            C1  C2
0    10.000000  32
1    13.103448  47
2    16.206897  84
3    19.310345  96
4    22.413793  76
5    25.517241  93
6    28.620690  58
7    31.724138  14
8    34.827586  36
9    37.931034  96
10   41.034483  75
11   44.137931  12
12   47.241379  63
13   50.344828  65
14   53.448276  61
15   56.551724  79
20   72.068966  47
21   75.172414  63
22   78.275862  46
23   81.379310  90
24   84.482759  68
25   87.586207  49
26   90.689655  23
27   93.793103  55
28   96.896552  24
29  100.000000  82

In [82]:
df10.drop(df10.index[5], inplace=True)
df10

            C1  C2
0    10.000000  32
1    13.103448  47
2    16.206897  84
3    19.310345  96
4    22.413793  76
6    28.620690  58
7    31.724138  14
8    34.827586  36
9    37.931034  96
10   41.034483  75
11   44.137931  12
12   47.241379  63
13   50.344828  65
14   53.448276  61
15   56.551724  79
20   72.068966  47
21   75.172414  63
22   78.275862  46
23   81.379310  90
24   84.482759  68
25   87.586207  49
26   90.689655  23
27   93.793103  55
28   96.896552  24
29  100.000000  82

In [83]:
df10=df10.iloc[3:,]
df10

            C1  C2
3    19.310345  96
4    22.413793  76
6    28.620690  58
7    31.724138  14
8    34.827586  36
9    37.931034  96
10   41.034483  75
11   44.137931  12
12   47.241379  63
13   50.344828  65
14   53.448276  61
15   56.551724  79
20   72.068966  47
21   75.172414  63
22   78.275862  46
23   81.379310  90
24   84.482759  68
25   87.586207  49
26   90.689655  23
27   93.793103  55
28   96.896552  24
29  100.000000  82

In [84]:
df10=df10.iloc[:-4,]
df10

           C1  C2
3   19.310345  96
4   22.413793  76
6   28.620690  58
7   31.724138  14
8   34.827586  36
9   37.931034  96
10  41.034483  75
11  44.137931  12
12  47.241379  63
13  50.344828  65
14  53.448276  61
15  56.551724  79
20  72.068966  47
21  75.172414  63
22  78.275862  46
23  81.379310  90
24  84.482759  68
25  87.586207  49

In [85]:
df10=df10.iloc[:10,]
df10

           C1  C2
3   19.310345  96
4   22.413793  76
6   28.620690  58
7   31.724138  14
8   34.827586  36
9   37.931034  96
10  41.034483  75
11  44.137931  12
12  47.241379  63
13  50.344828  65

In [86]:
df10

           C1  C2
3   19.310345  96
4   22.413793  76
6   28.620690  58
7   31.724138  14
8   34.827586  36
9   37.931034  96
10  41.034483  75
11  44.137931  12
12  47.241379  63
13  50.344828  65

In [87]:
df10.index[df10['C2']==95].tolist()

[]

In [88]:
df10.drop(df10.index[df10['C2']==95].tolist(),axis=0,inplace=True)
df10

           C1  C2
3   19.310345  96
4   22.413793  76
6   28.620690  58
7   31.724138  14
8   34.827586  36
9   37.931034  96
10  41.034483  75
11  44.137931  12
12  47.241379  63
13  50.344828  65

In [89]:
df10=df10.drop(df10[df10["C2"]==92].index)
df10

           C1  C2
3   19.310345  96
4   22.413793  76
6   28.620690  58
7   31.724138  14
8   34.827586  36
9   37.931034  96
10  41.034483  75
11  44.137931  12
12  47.241379  63
13  50.344828  65

In [90]:
df10=df10[df10.C2 !=89]
df10

           C1  C2
3   19.310345  96
4   22.413793  76
6   28.620690  58
7   31.724138  14
8   34.827586  36
9   37.931034  96
10  41.034483  75
11  44.137931  12
12  47.241379  63
13  50.344828  65

In [91]:
df10=df10[~(df10.C2.isin([21,72,54]))]
df10

           C1  C2
3   19.310345  96
4   22.413793  76
6   28.620690  58
7   31.724138  14
8   34.827586  36
9   37.931034  96
10  41.034483  75
11  44.137931  12
12  47.241379  63
13  50.344828  65

In [92]:
df10=df10[df10.C2.isin([76,23])]
df10

          C1  C2
4  22.413793  76

In [93]:
dict={'A':pd.Series([1,2,3,11], index=['a', 'b', 'c', 'd']),
      'B':pd.Series([1,2,3,4], index=['a','b','c','d'])}
df11=pd.DataFrame(dict)
df11

    A  B
a   1  1
b   2  2
c   3  3
d  11  4

In [94]:
df11.drop("d",axis=0,inplace=True)
df11

   A  B
a  1  1
b  2  2
c  3  3

In [95]:
df13 = pd.DataFrame({ 'ID' :[1,2,3,4] , 
                      'Name' :['Asif' , 'Basit' , 'Ross' , 'John'] , 
                       'location' : ['India' , 'Australia','UK' , 'US'] })
df13

   ID   Name   location
0   1   Asif      India
1   2  Basit  Australia
2   3   Ross         UK
3   4   John         US

In [96]:
ind = df13[((df13.Name == 'Ross') &(df13.ID == 3) & (df13.location == 'UK'))].index
df13.drop(ind,inplace=True)
df13

   ID   Name   location
0   1   Asif      India
1   2  Basit  Australia
3   4   John         US

# Data Selection in DataFrame

In [97]:
df

  Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [98]:
df.index=[1,2,3,4]
df

  Language  Rating
1     Java       1
2   Python       2
3        C       3
4      C++       4

In [99]:
df.loc[1]

Language    Java
Rating         1
Name: 1, dtype: object

In [100]:
df.iloc[1]

Language    Python
Rating           2
Name: 2, dtype: object

In [101]:
df.loc[1:2]

  Language  Rating
1     Java       1
2   Python       2

In [102]:
df.iloc[1:2]

  Language  Rating
2   Python       2

In [103]:
df.loc[df.Rating > 2]

  Language  Rating
3        C       3
4      C++       4

In [104]:
df1

     A
a  1.0
b  2.0
c  3.0
d  NaN

In [105]:
df1.loc['a']

A    1.0
Name: a, dtype: float64

In [106]:
df1.iloc['a']

TypeError: Cannot index by location index with a non-integer key

In [107]:
dframe

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,0.573780,0.210665,0.652831,0.505520,0.442947,0.717820,0.031134
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682

In [108]:
dframe['2020-01-10':'2020-01-22']

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,0.573780,0.210665,0.652831,0.505520,0.442947,0.717820,0.031134
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694

In [109]:
dframe.loc[:,['C1','C7']]

                  C1        C7
2020-01-20  0.573780  0.031134
2020-01-21  0.226988  0.370182
2020-01-22  0.707134  0.174694
2020-01-23  0.843586  0.810536
2020-01-24  0.980601  0.709060
2020-01-25  0.126868  0.824672
2020-01-26  0.185709  0.073682

In [110]:
dframe.loc['2020-01-20':'2020-01-22',['C1','C7']]

                  C1        C7
2020-01-20  0.573780  0.031134
2020-01-21  0.226988  0.370182
2020-01-22  0.707134  0.174694

In [111]:
dframe[(dframe['C1']>0.5) & (dframe['C4']>0.5)]

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,0.573780,0.210665,0.652831,0.505520,0.442947,0.717820,0.031134
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694

In [112]:
dframe.iloc[0][0]

np.float64(0.5737799694575375)

In [113]:
dframe.iloc[:,0:3]

                  C1        C2        C3
2020-01-20  0.573780  0.210665  0.652831
2020-01-21  0.226988  0.155256  0.744551
2020-01-22  0.707134  0.452713  0.538654
2020-01-23  0.843586  0.555243  0.399276
2020-01-24  0.980601  0.432747  0.229671
2020-01-25  0.126868  0.481129  0.140612
2020-01-26  0.185709  0.751848  0.092681

In [114]:
dframe.iloc[0][0]=10

In [115]:
dframe[dframe['C1'].isin([10,20])]

              C1        C2        C3       C4        C5       C6        C7
2020-01-20  10.0  0.210665  0.652831  0.50552  0.442947  0.71782  0.031134

# Set Value

In [116]:
dframe['c1']=888
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,0.652831,0.505520,0.442947,0.717820,0.031134,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682,888

In [117]:
dframe.at[0:3,'C6']=777

InvalidIndexError: You can only assign a scalar value not a <class 'int'>

In [ ]:
dframe

In [118]:
dframe.iat[0,2]=333
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,333.000000,0.505520,0.442947,0.717820,0.031134,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682,888

In [119]:
dframe.iloc[0,2]=555
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,0.717820,0.031134,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682,888

In [120]:


dframe1=dframe.copy(deep=True)
dframe1[(dframe['C1']>0.5)&(dframe['C4']>0.5)]=0
dframe1[dframe1['C1']==0]

             C1   C2   C3   C4   C5   C6   C7  c1
2020-01-20  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0
2020-01-22  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0

In [121]:
dframe1[dframe1['C1'].isin([0])]=99
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,0.717820,0.031134,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682,888

In [122]:
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,0.717820,0.031134,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682,888

In [123]:
dframe1[dframe['C1']==99]

Empty DataFrame
Columns: [C1, C2, C3, C4, C5, C6, C7, c1]
Index: []

# Dealing with NULL values

In [124]:
dframe.at[0:8, 'C7']= np.NaN
dframe.at[0:2, 'C6']= np.NaN
dframe.at[5:6, 'C5']= np.NaN
dframe

AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

In [125]:
dframe.notna()

              C1    C2    C3    C4    C5    C6    C7    c1
2020-01-20  True  True  True  True  True  True  True  True
2020-01-21  True  True  True  True  True  True  True  True
2020-01-22  True  True  True  True  True  True  True  True
2020-01-23  True  True  True  True  True  True  True  True
2020-01-24  True  True  True  True  True  True  True  True
2020-01-25  True  True  True  True  True  True  True  True
2020-01-26  True  True  True  True  True  True  True  True

In [126]:
dframe.isna()

               C1     C2     C3     C4     C5     C6     C7     c1
2020-01-20  False  False  False  False  False  False  False  False
2020-01-21  False  False  False  False  False  False  False  False
2020-01-22  False  False  False  False  False  False  False  False
2020-01-23  False  False  False  False  False  False  False  False
2020-01-24  False  False  False  False  False  False  False  False
2020-01-25  False  False  False  False  False  False  False  False
2020-01-26  False  False  False  False  False  False  False  False

In [127]:
dframe=dframe.fillna(1020)
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,0.717820,0.031134,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,0.714232,0.370182,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,0.162988,0.174694,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,0.810536,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,0.709060,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,0.488745,0.285296,0.824672,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,0.288393,0.073063,0.073682,888

In [128]:
import numpy as np

dframe.iloc[0:6, dframe.columns.get_loc('C7')] = np.nan
dframe.iloc[0:3, dframe.columns.get_loc('C6')] = np.nan
dframe.iloc[5:7, dframe.columns.get_loc('C5')] = np.nan

print(dframe)

                   C1        C2          C3        C4        C5        C6  \
2020-01-20  10.000000  0.210665  555.000000  0.505520  0.442947       NaN
2020-01-21   0.226988  0.155256    0.744551  0.460331  0.513807       NaN
2020-01-22   0.707134  0.452713    0.538654  0.795577  0.005927       NaN
2020-01-23   0.843586  0.555243    0.399276  0.020145  0.937514  0.457279
2020-01-24   0.980601  0.432747    0.229671  0.288931  0.243828  0.479726
2020-01-25   0.126868  0.481129    0.140612  0.281840       NaN  0.285296
2020-01-26   0.185709  0.751848    0.092681  0.194762       NaN  0.073063

                  C7   c1
2020-01-20       NaN  888
2020-01-21       NaN  888
2020-01-22       NaN  888
2020-01-23       NaN  888
2020-01-24       NaN  888
2020-01-25       NaN  888
2020-01-26  0.073682  888

In [129]:
dframe.fillna(value={'C5':123,'C6':789})

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,789.000000,NaN,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,789.000000,NaN,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,789.000000,NaN,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,NaN,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,NaN,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,123.000000,0.285296,NaN,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,123.000000,0.073063,0.073682,888

In [130]:
dframe.fillna(value={'C7':789},limit=1)

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,NaN,789.000000,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,NaN,NaN,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,NaN,NaN,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,NaN,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,NaN,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,NaN,0.285296,NaN,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,NaN,0.073063,0.073682,888

In [131]:
dframe.dropna()

Empty DataFrame
Columns: [C1, C2, C3, C4, C5, C6, C7, c1]
Index: []

In [132]:
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,NaN,NaN,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,NaN,NaN,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,NaN,NaN,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,NaN,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,NaN,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,NaN,0.285296,NaN,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,NaN,0.073063,0.073682,888

In [133]:
dframe.dropna(subset=['C5','C6'])

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,NaN,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,NaN,888

# Descriptive Statistics

In [134]:
dframe.fillna(55, inplace=True)
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,55.000000,55.000000,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,55.000000,55.000000,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,55.000000,55.000000,888
2020-01-23,0.843586,0.555243,0.399276,0.020145,0.937514,0.457279,55.000000,888
2020-01-24,0.980601,0.432747,0.229671,0.288931,0.243828,0.479726,55.000000,888
2020-01-25,0.126868,0.481129,0.140612,0.281840,55.000000,0.285296,55.000000,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,55.000000,0.073063,0.073682,888

In [135]:
dframe.mean()

C1      1.867269
C2      0.434229
C3     79.592207
C4      0.363872
C5     16.020575
C6     23.756481
C7     47.153383
c1    888.000000
dtype: float64

In [136]:
dframe.max()

C1     10.000000
C2      0.751848
C3    555.000000
C4      0.795577
C5     55.000000
C6     55.000000
C7     55.000000
c1    888.000000
dtype: float64

In [137]:
dframe.min()

C1      0.126868
C2      0.155256
C3      0.092681
C4      0.020145
C5      0.005927
C6      0.073063
C7      0.073682
c1    888.000000
dtype: float64

In [138]:
dframe.median()

C1      0.707134
C2      0.452713
C3      0.399276
C4      0.288931
C5      0.513807
C6      0.479726
C7     55.000000
c1    888.000000
dtype: float64

In [139]:
dframe.std()

C1      3.602511
C2      0.202434
C3    209.635259
C4      0.249943
C5     26.629517
C6     29.225940
C7     20.760197
c1      0.000000
dtype: float64

In [140]:
dframe.var()

C1       12.978083
C2        0.040979
C3    43946.941607
C4        0.062472
C5      709.131159
C6      854.155563
C7      430.985778
c1        0.000000
dtype: float64

In [141]:
dframe.quantile(0.50)

C1      0.707134
C2      0.452713
C3      0.399276
C4      0.288931
C5      0.513807
C6      0.479726
C7     55.000000
c1    888.000000
Name: 0.5, dtype: float64

In [142]:

dframe.quantile(0.75)

C1      0.912093
C2      0.518186
C3      0.641603
C4      0.482925
C5     27.968757
C6     55.000000
C7     55.000000
c1    888.000000
Name: 0.75, dtype: float64

In [143]:
dframe.quantile(0.75) - dframe.quantile(0.25)

C1     0.705745
C2     0.196480
C3     0.456461
C4     0.244624
C5    27.625370
C6    54.628712
C7     0.000000
c1     0.000000
dtype: float64

In [144]:
dframe.sum()

C1      13.070885
C2       3.039601
C3     557.145446
C4       2.547106
C5     112.144022
C6     166.295364
C7     330.073682
c1    6216.000000
dtype: float64

In [145]:
dframe.describe()

,C1,C2,C3,C4,C5,C6,C7,c1
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.0
mean,1.867269,0.434229,79.592207,0.363872,16.020575,23.756481,47.153383,888.0
std,3.602511,0.202434,209.635259,0.249943,26.629517,29.225940,20.760197,0.0
min,0.126868,0.155256,0.092681,0.020145,0.005927,0.073063,0.073682,888.0
25%,0.206348,0.321706,0.185142,0.238301,0.343387,0.371288,55.000000,888.0
50%,0.707134,0.452713,0.399276,0.288931,0.513807,0.479726,55.000000,888.0
75%,0.912093,0.518186,0.641603,0.482925,27.968757,55.000000,55.000000,888.0
max,10.000000,0.751848,555.000000,0.795577,55.000000,55.000000,55.000000,888.0

In [146]:
dframe.skew()

C1    2.595852
C2    0.029217
C3    2.645745
C4    0.564506
C5    1.229150
C6    0.374084
C7   -2.645751
c1    0.000000
dtype: float64

In [147]:
dframe.kurt()

C1    6.798204
C2   -0.133529
C3    6.999973
C4    0.587895
C5   -0.840381
C6   -2.799883
C7    7.000000
c1    0.000000
dtype: float64

In [148]:
dframe.corr

<bound method DataFrame.corr of                    C1        C2          C3        C4         C5         C6  \
2020-01-20  10.000000  0.210665  555.000000  0.505520   0.442947  55.000000
2020-01-21   0.226988  0.155256    0.744551  0.460331   0.513807  55.000000
2020-01-22   0.707134  0.452713    0.538654  0.795577   0.005927  55.000000
2020-01-23   0.843586  0.555243    0.399276  0.020145   0.937514   0.457279
2020-01-24   0.980601  0.432747    0.229671  0.288931   0.243828   0.479726
2020-01-25   0.126868  0.481129    0.140612  0.281840  55.000000   0.285296
2020-01-26   0.185709  0.751848    0.092681  0.194762  55.000000   0.073063

                   C7   c1
2020-01-20  55.000000  888
2020-01-21  55.000000  888
2020-01-22  55.000000  888
2020-01-23  55.000000  888
2020-01-24  55.000000  888
2020-01-25  55.000000  888
2020-01-26   0.073682  888  >

In [149]:
dframe.cov()

,C1,C2,C3,C4,C5,C6,C7,c1
C1,12.978083,-0.353387,751.801063,0.223063,-31.105188,48.627401,15.393654,0.0
C2,-0.353387,0.040979,-20.698625,-0.024940,3.319906,-4.421944,-2.907614,0.0
C3,751.801063,-20.698625,43946.941607,13.122829,-1444.384604,2893.350163,727.769373,0.0
C4,0.223063,-0.024940,13.122829,0.062472,-2.339745,6.101786,1.548098,0.0
C5,-31.105188,3.319906,-1444.384604,-2.339745,709.131159,-431.824071,-356.832722,0.0
C6,48.627401,-4.421944,2893.350163,6.101786,-431.824071,854.155563,216.807156,0.0
C7,15.393654,-2.907614,727.769373,1.548098,-356.832722,216.807156,430.985778,0.0
c1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

In [150]:
import statistics as at
dframe.iloc[3:6,0]=22
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,55.000000,55.000000,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,55.000000,55.000000,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,55.000000,55.000000,888
2020-01-23,22.000000,0.555243,0.399276,0.020145,0.937514,0.457279,55.000000,888
2020-01-24,22.000000,0.432747,0.229671,0.288931,0.243828,0.479726,55.000000,888
2020-01-25,22.000000,0.481129,0.140612,0.281840,55.000000,0.285296,55.000000,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,55.000000,0.073063,0.073682,888

In [151]:
import statistics as st

st.mean(dframe['C1'])

11.017118687434506

In [152]:
st.harmonic_mean(dframe['C1'])

0.6118443427162753

In [153]:
arr=np.array([1,2,3,4,5,6,7,8])
st.median(arr)

np.float64(4.5)

In [154]:
st.median_low(arr)

np.int64(4)

In [155]:
st.median_high(arr)

np.int64(5)

In [156]:
st.mode(dframe['C7'])

55.0

In [157]:
st.variance(dframe['C1'])

117.15795346011751

In [158]:
st.pvariance(dframe['C1'])

100.42110296581501

In [159]:
st.stdev(dframe['C1'])

10.823952765053878

In [160]:
st.pstdev(dframe['C1'])

10.021033028875566

# Apply function on Dataframe

In [161]:
dframe

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,55.000000,55.000000,888
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,55.000000,55.000000,888
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,55.000000,55.000000,888
2020-01-23,22.000000,0.555243,0.399276,0.020145,0.937514,0.457279,55.000000,888
2020-01-24,22.000000,0.432747,0.229671,0.288931,0.243828,0.479726,55.000000,888
2020-01-25,22.000000,0.481129,0.140612,0.281840,55.000000,0.285296,55.000000,888
2020-01-26,0.185709,0.751848,0.092681,0.194762,55.000000,0.073063,0.073682,888

In [162]:
dframe.apply(max)

C1     22.000000
C2      0.751848
C3    555.000000
C4      0.795577
C5     55.000000
C6     55.000000
C7     55.000000
c1    888.000000
dtype: float64

In [163]:
dframe.apply(min)

C1      0.185709
C2      0.155256
C3      0.092681
C4      0.020145
C5      0.005927
C6      0.073063
C7      0.073682
c1    888.000000
dtype: float64

In [164]:
dframe.apply(sum)

C1      77.119831
C2       3.039601
C3     557.145446
C4       2.547106
C5     112.144022
C6     166.295364
C7     330.073682
c1    6216.000000
dtype: float64

In [165]:
dframe.apply(np.sum)

C1      77.119831
C2       3.039601
C3     557.145446
C4       2.547106
C5     112.144022
C6     166.295364
C7     330.073682
c1    6216.000000
dtype: float64

In [166]:
dframe.apply(np.sum,axis=1)

2020-01-20    1564.159131
2020-01-21    1000.100933
2020-01-22    1000.500006
2020-01-23     967.369456
2020-01-24     966.674902
2020-01-25    1021.188877
2020-01-26     944.371745
Freq: D, dtype: float64

In [167]:
dframe.applymap(np.sqrt)

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,3.162278,0.458982,23.558438,0.710999,0.665542,7.416198,7.416198,29.799329
2020-01-21,0.476432,0.394026,0.862874,0.678477,0.716803,7.416198,7.416198,29.799329
2020-01-22,0.840913,0.672839,0.733931,0.891951,0.076989,7.416198,7.416198,29.799329
2020-01-23,4.690416,0.745146,0.631883,0.141933,0.968253,0.676224,7.416198,29.799329
2020-01-24,4.690416,0.657835,0.479240,0.537523,0.493789,0.692623,7.416198,29.799329
2020-01-25,4.690416,0.693635,0.374983,0.530886,7.416198,0.534131,7.416198,29.799329
2020-01-26,0.430940,0.867092,0.304436,0.441319,7.416198,0.270302,0.271444,29.799329

In [168]:
dframe.applymap(math.sqrt)

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,3.162278,0.458982,23.558438,0.710999,0.665542,7.416198,7.416198,29.799329
2020-01-21,0.476432,0.394026,0.862874,0.678477,0.716803,7.416198,7.416198,29.799329
2020-01-22,0.840913,0.672839,0.733931,0.891951,0.076989,7.416198,7.416198,29.799329
2020-01-23,4.690416,0.745146,0.631883,0.141933,0.968253,0.676224,7.416198,29.799329
2020-01-24,4.690416,0.657835,0.479240,0.537523,0.493789,0.692623,7.416198,29.799329
2020-01-25,4.690416,0.693635,0.374983,0.530886,7.416198,0.534131,7.416198,29.799329
2020-01-26,0.430940,0.867092,0.304436,0.441319,7.416198,0.270302,0.271444,29.799329

In [169]:
dframe.applymap(float)

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,10.000000,0.210665,555.000000,0.505520,0.442947,55.000000,55.000000,888.0
2020-01-21,0.226988,0.155256,0.744551,0.460331,0.513807,55.000000,55.000000,888.0
2020-01-22,0.707134,0.452713,0.538654,0.795577,0.005927,55.000000,55.000000,888.0
2020-01-23,22.000000,0.555243,0.399276,0.020145,0.937514,0.457279,55.000000,888.0
2020-01-24,22.000000,0.432747,0.229671,0.288931,0.243828,0.479726,55.000000,888.0
2020-01-25,22.000000,0.481129,0.140612,0.281840,55.000000,0.285296,55.000000,888.0
2020-01-26,0.185709,0.751848,0.092681,0.194762,55.000000,0.073063,0.073682,888.0

In [170]:
dframe.apply(lambda x:min(x))

C1      0.185709
C2      0.155256
C3      0.092681
C4      0.020145
C5      0.005927
C6      0.073063
C7      0.073682
c1    888.000000
dtype: float64

In [171]:
dframe.apply(lambda x:x*x)

,C1,C2,C3,C4,C5,C6,C7,c1
2020-01-20,100.000000,0.044380,308025.000000,0.255550,0.196202,3025.000000,3025.000000,788544
2020-01-21,0.051523,0.024104,0.554356,0.211905,0.263998,3025.000000,3025.000000,788544
2020-01-22,0.500039,0.204949,0.290149,0.632943,0.000035,3025.000000,3025.000000,788544
2020-01-23,484.000000,0.308294,0.159421,0.000406,0.878932,0.209104,3025.000000,788544
2020-01-24,484.000000,0.187270,0.052749,0.083481,0.059452,0.230137,3025.000000,788544
2020-01-25,484.000000,0.231485,0.019772,0.079434,3025.000000,0.081394,3025.000000,788544
2020-01-26,0.034488,0.565276,0.008590,0.037932,3025.000000,0.005338,0.005429,788544

# Merge Dataframes

In [172]:
daf1=pd.DataFrame({'id':['1','2','3','4','5'],'Name':['Asif','Basit','Bran','John','David']})
daf1

  id   Name
0  1   Asif
1  2  Basit
2  3   Bran
3  4   John
4  5  David

In [173]:
daf2=pd.DataFrame({'id':['1','2','3','4','5'],'Score':[40,60,80,90,70]})
daf2

  id  Score
0  1     40
1  2     60
2  3     80
3  4     90
4  5     70

In [174]:
pd.merge(daf1,daf2,on='id',how='inner')

  id   Name  Score
0  1   Asif     40
1  2  Basit     60
2  3   Bran     80
3  4   John     90
4  5  David     70

In [175]:
pd.merge(daf1,daf2,on='id',how='outer')

  id   Name  Score
0  1   Asif     40
1  2  Basit     60
2  3   Bran     80
3  4   John     90
4  5  David     70

In [176]:

pd.merge(daf1, daf2, on='id', how='left')

  id   Name  Score
0  1   Asif     40
1  2  Basit     60
2  3   Bran     80
3  4   John     90
4  5  David     70

In [177]:
pd.merge(daf1, daf2, on='id', how='right')

  id   Name  Score
0  1   Asif     40
1  2  Basit     60
2  3   Bran     80
3  4   John     90
4  5  David     70

# Importing multiple CSV files in DataFrame

In [181]:
import pandas as pd
import glob

# Folder path do, CSV file ka nahi
path = r'
filenames = glob.glob(path + "/*.csv")
print(filenames)

covid = pd.DataFrame()

for f in filenames:
    df = pd.read_csv(f)
    covid = pd.concat([covid, df], ignore_index=True, sort=True)

print(covid.shape)

['C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\data.csv', 'C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\Inc_Exp_Data.csv', 'C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\Movie-Rating.csv', 'C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\movie.csv', 'C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\rating.csv', 'C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\sales_data.csv', 'C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\student_info.csv', 'C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\tag.csv']

ParserError: Error tokenizing data. C error: Expected 1 fields in line 12, saw 2

In [ ]:
import pandas as pd
import glob

path = r'C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\data.csv'

filenames = glob.glob(path + "/*.csv")

print(filenames)

dfs = []

for f in filenames:
    df = pd.read_csv(f)
    dfs.append(df)

covid = pd.concate(dfs, ignore_index=True)

print(covid.head())
print(covid.tail())

In [189]:
import pandas as pd
import glob

path = r'C:\\Users\\Aisharani Patro\\OneDrive\\Desktop\\data.csv'

filenames = glob.glob(path + "/*.csv")

print(filenames)

dfs = []

for f in filenames:
    try:
        df = pd.read_csv(f)
        dfs.append(df)
    except Exception as e:
        print("Error in file:", f)
        print(e)

covid = pd.concat(dfs, ignore_index=True)

print(covid.head())

[]

ValueError: No objects to concatenate